TEST_VALUE:
  name: Rosiiie
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a4f430d1bd269013
  FEISHU_APP_SECRET: d0TCKhpzo9F6FILYFxGYidUmyhd0hKFe
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
MONGODB_CONFIG:
  name: "nest_Database"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://localhost:27017"   # 数据库链接地址
  username: "user"                   # 数据库链接用户名
  password: "password"                 # 数据库链接密码
  database: "nest_Database"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
